### ISSUE TITLE
Design Home page

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#155]
## Objective
TBD.

**Comment by LongoOfficial** [comment]
these designs were based on the old IA:

**Comment by LongoOfficial** [comment]
![home_desktop](https://user-images.githubusercontent.com/41894292/46788268-117cf800-cd3a-11e8-90eb-4dadb9d0f5a6.png)
![home_mobile](https://user-images.githubusercontent.com/41894292/46788269-117cf800-cd3a-11e8-903d-428c0b0a6025.png)
