### ISSUE TITLE
Review Documentation Overview Pages

### ISSUE THREAD

**Issue by LongoOfficial** [jungvonmatt/amp.dev#180]
## Objective
Gather feedback on the current design for overview pages in the documentation section.

## Background
In our last call on 10/5 we agreed to aggregate feedback on all current designs in order to find the best solution possible. For history see #171.

In the following comments you'll find the information architecture for the documentation overview pages and the corresponding design.

## Tasks
- [ ] Refine information architecture (@lenottermann) 
- [ ] Refine design (@LongoOfficial)

/cc @spacedino @pbakaus @CrystalFaith

**Comment by LongoOfficial** [comment]
<img width="965" alt="guides and tutorials overview ia" src="https://user-images.githubusercontent.com/41894292/46620673-a1962400-cb25-11e8-8708-7fc87e8a33fc.png">

**Comment by LongoOfficial** [comment]
![guides and tutorials overview desktop](https://user-images.githubusercontent.com/41894292/46620686-aeb31300-cb25-11e8-8b1e-e66579152df9.png)
![guides and tutorials overview mobile](https://user-images.githubusercontent.com/41894292/46620690-b1156d00-cb25-11e8-8231-91befb60ba7f.png)

**Comment by LongoOfficial** [comment]
![guides and tutorials overview _desktop](https://user-images.githubusercontent.com/41894292/46620737-d1ddc280-cb25-11e8-8d69-d7cae741be5e.png)
![guides and tutorials overview _mobile](https://user-images.githubusercontent.com/41894292/46620742-d904d080-cb25-11e8-9ac8-8a08ac091584.png)

**Comment by pbakaus** [comment]
@LongoOfficial @matthiasrohmer my feedback, re-posted from previous wrong location:

- the individual doc page looks fine, but I'm missing the callouts, as well as a mobile mock (I don't actually know how to solve the sidenav/table of contents issue)
- The doc overview page is wasted potential, imho. It's a bunch of cards right now, but it could be so much more: The cards take a ton of space, don't really work well on mobile, and are too uniform for the kind of content we'd ideally like on the overview page. In my opinion, the doc overview page deserves to be the ideal landing page for developers, explaining how to use the docs, and giving you a meaningful quickstart.

A couple things I'd love to see on the docs overview page:

- The content from https://www.ampproject.org/docs/getting_started/quickstart, but organized better:
- Where do I start?
- What are the different ways to learn? (Video, Guides, Tutorials, Samples, ...)
- What's the ideal workflow? (From scratch, CMS, tools..)

Does that make sense? Curious to hear @CrystalFaith's thoughts too.

**Comment by matthiasrohmer** [comment]
@sebastianbenz I know you have some ideas on this as well 😉Would be great if you could quickly outline them for Longo and Lenny.

**Comment by LongoOfficial** [comment]
this is the **components** overview page:

<img width="631" alt="03 components overview __ia" src="https://user-images.githubusercontent.com/41894292/46684822-38311680-cbf4-11e8-85a4-6bbd272871e8.png">

![03 components overview _desktop](https://user-images.githubusercontent.com/41894292/46684871-58f96c00-cbf4-11e8-9b3a-85255461cc70.png)

![03 components overview _mobile](https://user-images.githubusercontent.com/41894292/46684886-6282d400-cbf4-11e8-95a8-708a5b25fee5.png)

**Comment by LongoOfficial** [comment]
this is the **examples** overview page:

<img width="582" alt="05 examples overview __ia" src="https://user-images.githubusercontent.com/41894292/46684929-86deb080-cbf4-11e8-90ea-ac387e251f65.png">

![05 examples overview _desktop](https://user-images.githubusercontent.com/41894292/46684936-8d6d2800-cbf4-11e8-967f-729ce070e5af.png)

![05 examples overview _mobile](https://user-images.githubusercontent.com/41894292/46684942-91994580-cbf4-11e8-984f-ceff5be9a865.png)

**Comment by LongoOfficial** [comment]
this is the **templates** overview page:

<img width="578" alt="07 templates overview __ia" src="https://user-images.githubusercontent.com/41894292/46685011-bbeb0300-cbf4-11e8-85f2-1783b88d9f0a.png">

![07 templates overview _desktop](https://user-images.githubusercontent.com/41894292/46685020-c0172080-cbf4-11e8-9cdf-0aa5af5f6485.png)

![07 templates overview _mobile](https://user-images.githubusercontent.com/41894292/46685098-e89f1a80-cbf4-11e8-8b09-9720b3a42153.png)

**Comment by sebastianbenz** [comment]
Few comments:

* Agree with Paul, we should better use the space.
* In general: a long list of cards is very hard to comprehend, both on mobile and desktop.
* Samples & Components: mobile should focus on filter and search. Suggestion: show getting started and a few highlights (maybe each in a one row carousel). The next thing should be the filter ui + a text search field. 
* Templates overview page works well.
* Can we use background colours to categorise the different components / samples? This would make it easier to scan a result list.
