### ISSUE TITLE
Implement CM_KPIs_Statistics

### ISSUE THREAD

**Issue by matthiasrohmer** [jungvonmatt/amp.dev#49]
## Objective

Implement the attached design in a way that enables the user to swipe through the cards.

## Background

![cm_kpis](https://user-images.githubusercontent.com/12857772/44137169-ade0dcf4-a06f-11e8-9c4c-268ca80307e4.png)

This could either be implemented by using CSS Scroll Snap Points or `<amp-carousel>`.

## Tasks
- [x] Implement component
- [x] Setup demo page
- [x] Accessibility to at least AA standard

**Comment by keevcodes** [comment]
Some accessibility features were added, however I feel that this may be an ongoing endeavour during this sprint. I would like to set up a time where we could get together to address any remaining issues with accessibility on all components sometime during this sprint.
